import logging
from typing import Optional

from app.services.modbus_client import read_plant_state
from app.models import Reading
from sqlmodel import Session
from app.database import engine
from app.config import Settings

logger = logging.getLogger(__name__)
settings = Settings()


async def poll_once() -> Optional[Reading]:
    """Fetch the current plant state and persist a `Reading` record.

    Returns the created `Reading` on success or `None` if the read fails.
    This function intentionally swallows transient connection errors and logs them
    so the poller loop can continue attempting later.
    """
    try:
        water_level, pump_status, valve_status = await read_plant_state(host=settings.plant_host, port=settings.plant_port)
    except Exception as exc:  # pragma: no cover - network behaviour
        logger.warning("poll_once: failed to read plant state: %s", exc)
        return None

    reading = Reading(water_level=water_level, pump_state=bool(pump_status), valve_state=bool(valve_status))
    try:
        with Session(engine) as session:
            session.add(reading)
            session.commit()
            # refresh to populate autogenerated fields (id, timestamps) while
            # the instance is still attached to the session
            try:
                session.refresh(reading)
            except Exception:
                # refresh may fail for some backends; ignore and continue
                pass
            # capture primitives to avoid accessing attributes on a detached instance
            persisted_id = getattr(reading, "id", None)
            persisted_water = getattr(reading, "water_level", None)
    except Exception as exc:  # pragma: no cover - DB issues
        logger.exception("poll_once: failed to persist reading: %s", exc)
        return None

    logger.debug("poll_once: persisted reading id=%s water=%s", persisted_id, persisted_water)
    return reading


